export const SEARCH_USERS = 'SEARCH_USERS';
export const GET_USER = 'GET_USER';
export const CLEAR_USERS = 'CLEAR_USERS';
export const GET_REPOS_SORT_CREATED = 'GET_REPOS_SORT_CREATED';
export const GET_REPOS_SORT_STARS = 'GET_REPOS_SORT_STARS';
export const SET_LOADING = 'SET_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
